{ ... }:

{
  users.users.pi = {
    isNormalUser = true;
    extraGroups = [
      "wheel"
      "networkmanager"
    ];

    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGZ81uLlrCQ0LztEOhSINdmLomNfqnB+dCL6AVAvHfaH"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJF33QRynQt0/dAOfdk5uZWdOtevEOeHKv5jKZhVF8mb Generated By Termius"
      "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC8fdRfHmwHeihC8NGvqKtkrk6Zvkm3vcsjvz+hul5Mgz+9vTxDQ79e1/PUn/VrV+7WWjDasRQimV07PXDGAvZSJS80uMmwlhhigA0vDq6zaiumHRocm5PD1ZWKsH0Dh2qkA2COWQy6ogW6ZJDVNQJN8JecHPilSIu6bUnnCAs6W9pS5/g//1LXD2D4+Rzy5LDyvtlHOOtHWyWeM0PokZ5SC/x7c2TxOXWpTnDJlb7LBbvUUWZyZ2e56waUs9ahVpm8XBsJ5DECTD27jnQwmPEW0ZdmkzVuPUglpMnVGyFA3iixfYvqFw8zT3+mNVbIEsUYws07xzaPLs0O1dbdatu7kxn6iflt9xp9iEzmJ5EJ6vqKsy9FJ1DgxjivLa9zTPMOfaErZYlArq1uohGINcA0eT73pyHlPKzn46gdQ6FEU9Zft0evxGyXN5eZdIX1oZsm/RyFZEAXJxjMnNccG1bMQN+PK5/6xt98iJYk+bjTG/+uH22iBxfqG5h+5qXpG8s= adrien@Adriens-MBP"
    ];
  };
}
